# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 19:03
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odamaster',
            name='default_permission',
            field=models.CharField(default=30, max_length=2),
        ),
        migrations.AlterField(
            model_name='binaryfile',
            name='the_file',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='binaryoptions',
            name='extra_options',
            field=models.CharField(default='{"flags" : [] }', max_length=256),
        ),
        migrations.AlterField(
            model_name='odamaster',
            name='ipAddress',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='odamaster',
            name='project_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='odauser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
