# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odaweb', '0002_auto_20171124_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryfile',
            name='idb_file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
