# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('odaweb', '0003_binaryfile_idb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdaMasterPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='odamaster',
            options={'permissions': (('read_odamaster', 'Can read this ODA Master'), ('edit_odamaster', 'Can edit this ODA Master'))},
        ),
        migrations.AddField(
            model_name='odamasterpermission',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odaweb.OdaMaster'),
        ),
        migrations.AddField(
            model_name='odamasterpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='odamasterpermission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odamaster',
            name='permissions',
            field=models.ManyToManyField(through='odaweb.OdaMasterPermission', to='auth.Permission'),
        ),
    ]
